CREATE ROLE "IWFM_ROLE" NOT IDENTIFIED;
GRANT CREATE ANY TABLE TO "IWFM_ROLE";
GRANT DELETE ANY TABLE TO "IWFM_ROLE";
GRANT INSERT ANY TABLE TO "IWFM_ROLE";
GRANT SELECT ANY TABLE TO "IWFM_ROLE";
GRANT UPDATE ANY TABLE TO "IWFM_ROLE";
GRANT "CONNECT" TO "IWFM_ROLE";
Grant resource to TO "IWFM_ROLE";